# Generated by Django 3.2.11 on 2022-01-08 13:56

from django.db import migrations, models
import uploadfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=uploadfile.models.productFile),
        ),
    ]
