# Generated by Django 3.2.11 on 2022-01-08 17:12

from django.db import migrations, models
import uploadfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=uploadfile.models.productFile)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
